### ISSUE TITLE
Schema and Ruleset Equality

### ISSUE THREAD

**Issue by hayfield** [IATI/pyIATI#245]
For the completion of #244, it is necessary to implement `Schema` and `Ruleset` equality checks. This Issue details the design of these initial checks (they may change over time).

**Schema**

- [x] `_schema_base_tree` must be the same
- [x] `codelists` must be the same
- [x] `rulesets` must be the same
- [x] `_source_path` may be different

**Ruleset**

- [x] `rules` must be the same

**Rule**

- [x] `name` must be the same
- [x] `context` must be the same
- [x] `case` must be the same

**Comment by hayfield** [comment]
In `0.3.0`.
